usethis::use_package('rmutil')
usethis::use_package('MASS')
usethis::use_package('mvtnorm')
usethis::use_package('stats')
usethis::use_package('graphics')
usethis::use_build_ignore("devtools_history.R")
